# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-19 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custdtil',
            name='id',
        ),
        migrations.RemoveField(
            model_name='driverdtil',
            name='id',
        ),
        migrations.AlterField(
            model_name='custdtil',
            name='Cust_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='driverdtil',
            name='Driver_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
