# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-19 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_auto_20170919_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custdtil',
            name='user_lat',
            field=models.IntegerField(max_length=250),
        ),
        migrations.AlterField(
            model_name='custdtil',
            name='user_long',
            field=models.IntegerField(max_length=250),
        ),
    ]
