# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-20 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_auto_20170919_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_id',
            name='Driver_ID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='master.DriverDtil'),
        ),
    ]
